name: minitts-dev

services:
  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  rabbitmq:
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      # - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  seaweedfs:
    ports:
      - "${SEAWEEDFS_S3_ENDPOINT_PORT:-8333}:8333"
      - "${SEAWEEDFS_MASTER_UI_PORT:-9333}:9333"
      - "${SEAWEEDFS_FILER_UI_PORT:-8888}:8888"
