name: minitts
services:
  caddy:
    image: caddy:2.11-alpine
    ports:
      - "3000:80"
    volumes:
      - ./misc/Caddyfile:/etc/caddy/Caddyfile
      - ./misc/index.html:/usr/share/caddy/index.html
    depends_on:
      - api
      - redisinsight
      - rabbitmq
      - pgadmin

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:3.4
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_USERNAME=default
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: elestio/pgadmin:REL-9_14
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

  soprano:
    build: ./soprano

  api:
    build: ./api
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - redis
      - postgres
      - rabbitmq
      - soprano

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:
