start:
    HF_HUB_VERBOSITY=error HF_HUB_DISABLE_PROGRESS_BARS=1 granian --interface asgi \
        --host 0.0.0.0 \
        --port 8081 \
        --loop uvloop \
        --no-reload \
        --no-ws \
        --metrics \
        --runtime-threads 8 \
        endpoint:app

preload:
    python ./scripts/preload_model.py