[project]
name = "core"
version = "0.1.0"
# description = "Add your description here"
# readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "pydantic>=2.13.3",
    "sqlalchemy[asyncio]>=2.0.49",
    "sqlmodel>=0.0.38",
]

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"

[project.optional-dependencies]
migration = [
    "alembic>=1.18.4",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
]
